#!/usr/bin/env node
'use strict';

// Generates one JSON Canvas per top-level topic: notes grouped by sub-tag,
// edges from `related`. Deterministic — no model call, read-only against notes.
//
//   node canvas.js [topic] [--dry-run] [--relayout]

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const dagre = require('@dagrejs/dagre');

const C = require('./lib/config.js');
const { readTaxonomy, topLevelNodes } = require('./lib/taxonomy.js');
const { splitNote, parseFm } = require('./lib/frontmatter.js');
const { parseRelated } = require('./lib/links.js');

const log = (...a) => console.log(...a);
const warn = (...a) => console.warn('  !', ...a);
const rel = (f) => path.relative(C.VAULT, f);

const NODE_W = 400, NODE_H = 200, GUTTER = 40, PAD = 40;

// Stable ids: regenerating must not churn the file or lose manual positions.
const hash = (s) => crypto.createHash('sha1').update(s).digest('hex').slice(0, 16);
const nodeId = (vaultPath) => hash(`note:${vaultPath}`);
const groupId = (topic, sub) => hash(`group:${topic}/${sub}`);
const edgeId = (from, to) => hash(`edge:${from}->${to}`);
const TITLE_ID = (topic) => hash(`title:${topic}`);

const MARKER = 'generated by cappy/canvas.js — move nodes freely, positions are kept';

function walk(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, out);
    else if (e.isFile() && e.name.endsWith('.md')) out.push(p);
  }
  return out;
}

// Only filed notes count. `tags` is written solely by accept.js, so a note
// carrying real tags has been through review by construction.
function loadNotes() {
  const notes = [];
  const byTitle = new Map();
  const ambiguous = new Set();
  for (const file of walk(C.NOTES_DIR)) {
    let data, error;
    try { ({ data, error } = parseFm(splitNote(fs.readFileSync(file, 'utf8')).fmText)); }
    catch (e) { warn(`unreadable, not on any canvas: ${rel(file)} — ${e.message}`); continue; }
    // A note that silently vanishes from a canvas because of a typo is worse
    // than a loud one.
    if (error) { warn(`unparseable frontmatter, not on any canvas: ${rel(file)} — ${error}`); continue; }
    const tags = Array.isArray(data.tags) ? data.tags.filter((t) => typeof t === 'string') : [];
    if (data.status !== 'filed' || tags.length === 0) continue;
    const note = {
      file, vaultPath: rel(file), title: path.basename(file, '.md'), tags,
      related: Array.isArray(data.related) ? data.related : [],
    };
    notes.push(note);
    for (const key of [note.title, ...(Array.isArray(data.aliases) ? data.aliases : [])]) {
      if (typeof key !== 'string' || !key.trim()) continue;
      if (byTitle.has(key.trim())) ambiguous.add(key.trim());
      else byTitle.set(key.trim(), note);
    }
  }
  for (const a of ambiguous) warn(`ambiguous title "${a}" — links to it are skipped`);
  for (const a of ambiguous) byTitle.delete(a);
  return { notes, byTitle };
}

// Group by the segment immediately under the topic: ai/llm/rag -> "llm".
function subGroup(topic, tags) {
  for (const t of tags) {
    if (t === topic) continue;
    if (t.startsWith(`${topic}/`)) return t.slice(topic.length + 1).split('/')[0];
  }
  return 'Other';
}

const inTopic = (tags, topic) => tags.some((t) => t === topic || t.startsWith(`${topic}/`));

function buildGraph(topic, notes, byTitle) {
  const members = notes.filter((n) => inTopic(n.tags, topic));
  const ids = new Set(members.map((n) => nodeId(n.vaultPath)));
  const edges = [];
  const seen = new Set();
  let dropped = 0;

  for (const n of members) {
    for (const raw of n.related) {
      const parsed = parseRelated(raw);
      if (!parsed) continue;
      const target = byTitle.get(parsed.title);
      if (!target) { dropped++; continue; }
      const from = nodeId(n.vaultPath), to = nodeId(target.vaultPath);
      if (from === to || !ids.has(to)) { dropped++; continue; }   // cross-topic
      const key = `${from}->${to}`;
      if (seen.has(key)) continue;
      seen.add(key);
      edges.push({ id: edgeId(from, to), fromNode: from, toNode: to, ...(parsed.label ? { label: parsed.label } : {}) });
    }
  }
  return { members, edges, dropped };
}

// One dagre pass per group, then the groups are stacked. A single compound
// pass lets dagre interleave clusters, and a group box drawn round the result
// can end up entirely containing its neighbour — which in Obsidian means
// dragging one group drags the other. Stacking makes overlap impossible.
function layout(topic, members, edges, previous, relayout) {
  const byGroup = new Map();
  for (const n of members) {
    const sub = subGroup(topic, n.tags);
    if (!byGroup.has(sub)) byGroup.set(sub, []);
    byGroup.get(sub).push(n);
  }

  const groups = new Map();
  const placed = new Map();
  let originY = 0;

  for (const [sub, groupMembers] of [...byGroup].sort((a, b) => a[0].localeCompare(b[0]))) {
    groups.set(sub, groupId(topic, sub));
    const ids = new Set(groupMembers.map((n) => nodeId(n.vaultPath)));

    const g = new dagre.graphlib.Graph();
    g.setGraph({ rankdir: 'LR', nodesep: 40, ranksep: 120 });
    g.setDefaultEdgeLabel(() => ({}));
    for (const id of ids) g.setNode(id, { width: NODE_W, height: NODE_H });
    // Only intra-group edges shape the layout; cross-group edges still render.
    for (const e of edges) if (ids.has(e.fromNode) && ids.has(e.toNode)) g.setEdge(e.fromNode, e.toNode);
    dagre.layout(g);

    // dagre reports centres; JSON Canvas uses top-left. Normalise to 0,0.
    const local = new Map();
    let minX = Infinity, minY = Infinity;
    for (const id of ids) {
      const d = g.node(id);
      const box = { x: Math.round(d.x - NODE_W / 2), y: Math.round(d.y - NODE_H / 2), width: NODE_W, height: NODE_H };
      local.set(id, box);
      minX = Math.min(minX, box.x); minY = Math.min(minY, box.y);
    }

    let maxY = 0;
    for (const [id, box] of local) {
      box.x += PAD - minX;
      box.y += originY + PAD - minY;
      maxY = Math.max(maxY, box.y + box.height);
    }
    originY = maxY + PAD * 2 + GUTTER;

    for (const n of groupMembers) {
      const id = nodeId(n.vaultPath);
      const prev = relayout ? null : previous.get(id);
      placed.set(id, prev || local.get(id));
    }
  }

  // New nodes must not land on top of preserved ones; nudge only the new.
  const keptIds = new Set([...placed.keys()].filter((id) => !relayout && previous.has(id)));
  const fixed = [...keptIds].map((id) => placed.get(id));
  for (const [id, box] of placed) {
    if (keptIds.has(id)) continue;
    let guard = 0;
    while (fixed.some((f) => overlaps(f, box)) && guard++ < 500) box.y += NODE_H + GUTTER;
    fixed.push(box);
  }

  return { placed, groups };
}

const overlaps = (a, b) =>
  a.x < b.x + b.width && b.x < a.x + a.width &&
  a.y < b.y + b.height && b.y < a.y + a.height;

function buildCanvas(topic, members, edges, placed, groups) {
  const nodes = [];
  const bounds = new Map();

  for (const n of members) {
    const id = nodeId(n.vaultPath);
    const box = placed.get(id);
    nodes.push({ id, type: 'file', file: n.vaultPath, ...box });
    const sub = subGroup(topic, n.tags);
    const b = bounds.get(sub) || { minX: Infinity, minY: Infinity, maxX: -Infinity, maxY: -Infinity };
    b.minX = Math.min(b.minX, box.x); b.minY = Math.min(b.minY, box.y);
    b.maxX = Math.max(b.maxX, box.x + box.width); b.maxY = Math.max(b.maxY, box.y + box.height);
    bounds.set(sub, b);
  }

  // Groups are recomputed every run: they carry no layout worth preserving.
  const groupNodes = [];
  for (const [sub, b] of bounds) {
    groupNodes.push({
      id: groups.get(sub), type: 'group', label: sub,
      x: b.minX - PAD, y: b.minY - PAD,
      width: (b.maxX - b.minX) + PAD * 2, height: (b.maxY - b.minY) + PAD * 2,
    });
  }

  const top = Math.min(...groupNodes.map((g) => g.y), 0);
  const left = Math.min(...groupNodes.map((g) => g.x), 0);
  const title = {
    id: TITLE_ID(topic), type: 'text',
    text: `# ${topic}\n\n${MARKER}`,
    x: left, y: top - 160, width: 640, height: 120,
  };

  // Groups first so Obsidian paints them behind the file nodes.
  return { nodes: [...groupNodes, title, ...nodes], edges };
}

function readPrevious(file) {
  const positions = new Map();
  if (!fs.existsSync(file)) return { positions, owned: true, existed: false };
  let parsed;
  try { parsed = JSON.parse(fs.readFileSync(file, 'utf8')); }
  catch { return { positions, owned: false, existed: true }; }
  const owned = (parsed.nodes || []).some((n) => n.type === 'text' && typeof n.text === 'string' && n.text.includes(MARKER));
  for (const n of parsed.nodes || []) {
    if (n.type === 'file' && typeof n.x === 'number') {
      positions.set(n.id, { x: n.x, y: n.y, width: n.width || NODE_W, height: n.height || NODE_H });
    }
  }
  return { positions, owned, existed: true };
}

function writeCanvas(file, canvas, dryRun) {
  const content = JSON.stringify(canvas, null, 2) + '\n';
  if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === content) return 'unchanged';
  if (dryRun) return 'would-write';
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const tmp = path.join(path.dirname(file), `.${path.basename(file)}.tmp.${process.pid}`);
  fs.writeFileSync(tmp, content, 'utf8');
  try { fs.renameSync(tmp, file); }
  catch (e) { fs.rmSync(tmp, { force: true }); throw e; }
  return 'written';
}

function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const relayout = args.includes('--relayout');
  const only = args.filter((a) => !a.startsWith('--'))[0];

  const { tags, rejected } = readTaxonomy(C.TAXONOMY_FILE);
  for (const r of rejected) warn('ignored taxonomy line:', JSON.stringify(r));
  if (!fs.existsSync(C.NOTES_DIR)) { warn('no notes dir:', C.NOTES_DIR); return; }

  const { notes, byTitle } = loadNotes();
  let topics = topLevelNodes(tags);
  if (only) {
    if (!topics.includes(only)) { warn(`no such top-level topic: ${only}`); process.exitCode = 1; return; }
    topics = [only];
  }

  log(`${dryRun ? '[dry-run] ' : ''}${notes.length} filed note(s), ${topics.length} topic(s)${relayout ? ', relayout' : ''}\n`);

  const counts = {};
  for (const topic of topics) {
    const { members, edges, dropped } = buildGraph(topic, notes, byTitle);
    const file = path.join(C.MAPS_DIR, `${topic}.canvas`);

    if (members.length === 0) {
      if (fs.existsSync(file)) warn(`${rel(file)}: no filed notes under #${topic} any more (left in place)`);
      continue;
    }
    const prev = readPrevious(file);
    if (prev.existed && !prev.owned) { warn(`not generated by us, leaving alone: ${rel(file)}`); continue; }

    const { placed, groups } = layout(topic, members, edges, prev.positions, relayout);
    const canvas = buildCanvas(topic, members, edges, placed, groups);
    const kept = relayout ? 0 : [...prev.positions.keys()].filter((id) => placed.has(id)).length;
    const r = writeCanvas(file, canvas, dryRun);
    counts[r] = (counts[r] || 0) + 1;

    log(`  ${r.padEnd(11)} ${rel(file)}`);
    log(`              ${members.length} note(s), ${new Set(members.map((n) => subGroup(topic, n.tags))).size} group(s), ${edges.length} edge(s), ${kept} position(s) kept` +
        (dropped ? `, ${dropped} link(s) dropped as cross-topic or unresolved` : ''));
  }
  const summary = Object.entries(counts).map(([k, v]) => `${v} ${k}`).join(', ');
  log(`\n${summary || 'nothing to do'}`);
}

if (require.main === module) main();

module.exports = { subGroup, buildGraph, nodeId, groupId, edgeId, loadNotes, overlaps };
