#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const C = require('./lib/config.js');
const { readTaxonomy, topLevelNodes } = require('./lib/taxonomy.js');

const log = (...a) => console.log(...a);
const warn = (...a) => console.warn('  !', ...a);
const rel = (f) => path.relative(C.VAULT, f);

// Only files carrying this marker are ever overwritten. Anything else in
// _maps/ is treated as the human's and left alone.
const MARKER = '%%generated by cappy/maps.js — edits will be overwritten%%';

function mapNote(node) {
  return `${MARKER}

Every note tagged \`#${node}\`, nested tags included. \`tags\` is only written
when a note is filed, so this is the filed set by construction.

\`\`\`base
filters:
  and:
    - file.hasTag("${node}")
views:
  - type: list
    name: ${node}
    order:
      - file.name
\`\`\`
`;
}

function reviewNote() {
  return `${MARKER}

Notes the classifier has proposed tags for. Open one, correct \`proposed_tags\`,
\`related\` and \`new_tag_proposals\` if needed, then tick \`approve\`.

\`\`\`base
filters:
  and:
    - note.status == "proposed"
views:
  - type: table
    name: Needs review
    order:
      - file.name
      - note.approve
      - note.proposed_tags
      - note.new_tag_proposals
      - note.classifier_note
\`\`\`
`;
}

// Write only when the content actually changes — an unnecessary write is an
// unnecessary iCloud sync, and churns mtimes the settle window depends on.
// Match loosely, on any name this project has shipped under: rewording the
// marker must never make us disown files we wrote, since we are not allowed to
// delete them and the human would have to clean them up by hand.
const OWNED = /(cappy|vault-pipeline)\/maps\.js/;

function writeGenerated(file, content, dryRun) {
  if (fs.existsSync(file)) {
    const cur = fs.readFileSync(file, 'utf8');
    if (!OWNED.test(cur.split('\n', 1)[0])) { warn('not generated by us, leaving alone:', rel(file)); return 'skipped'; }
    if (cur === content) return 'unchanged';
  }
  if (dryRun) return 'would-write';
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const tmp = path.join(path.dirname(file), `.${path.basename(file)}.tmp.${process.pid}`);
  fs.writeFileSync(tmp, content, 'utf8');
  try { fs.renameSync(tmp, file); }
  catch (e) { fs.rmSync(tmp, { force: true }); throw e; }
  return 'written';
}

function main() {
  const dryRun = process.argv.includes('--dry-run');
  const { tags, rejected } = readTaxonomy(C.TAXONOMY_FILE);
  for (const r of rejected) warn('ignored taxonomy line:', JSON.stringify(r));

  const nodes = topLevelNodes(tags);
  log(`${dryRun ? '[dry-run] ' : ''}${nodes.length} top-level node(s): ${nodes.join(', ')}\n`);

  const counts = {};
  const bump = (k) => { counts[k] = (counts[k] || 0) + 1; };

  for (const node of nodes) {
    const file = path.join(C.MAPS_DIR, `${node}.md`);
    const r = writeGenerated(file, mapNote(node), dryRun);
    bump(r);
    if (r !== 'unchanged') log(`  ${r.padEnd(11)} ${rel(file)}`);
  }

  const reviewFile = path.join(C.VAULT, '_system', 'Review.md');
  const r = writeGenerated(reviewFile, reviewNote(), dryRun);
  bump(r);
  if (r !== 'unchanged') log(`  ${r.padEnd(11)} ${rel(reviewFile)}`);

  // Never delete: a map for a node the taxonomy no longer has is the human's
  // problem to resolve, not ours to silently remove.
  if (fs.existsSync(C.MAPS_DIR)) {
    const known = new Set(nodes.map((n) => `${n}.md`));
    for (const f of fs.readdirSync(C.MAPS_DIR)) {
      if (f.endsWith('.md') && !known.has(f)) warn('stale map, no such top-level node:', rel(path.join(C.MAPS_DIR, f)));
    }
  }

  log('\n' + Object.entries(counts).map(([k, v]) => `${v} ${k}`).join(', '));
}

main();
